### PR TITLE
Issue 2: Integration tests

### LINKED ISSUE #2: Integration tests
Once #1 is in place, it should be relatively easy to write a set of integration tests that validate whether or not the desired auth behaviors are in place.  Obviously they would initially fail until the module is complete.

### PR DESCRIPTION
**Pull request by twistedstream**
Please merge PR #12 before this PR since its feature branch ([`issue-2`](https://github.com/twistedstream/nginx-jwt/tree/issue-2)) was branched off of #12's ([`issue-11`] feature branch (https://github.com/twistedstream/nginx-jwt/tree/issue-11))

Closes #2

### CODE REVIEW

File: test/test_integration.js [hunk 1]
```diff
@@ -0,0 +1,54 @@
+/* global describe, it */
+
+'use strict';
+
+var request = require('super-request');
+var jws = require('jws');
```
Comment (woloski) [inline test/test_integration.js]: I would use `jsonwebtoken` module

**Comment by twistedstream** [comment]
FYI most of the integration tests at failing, which is by design. They will start passing as the module gets implemented.

**Comment by twistedstream** [comment]
@woloski: switched from `jwt` to `jsonwebtoken` in the integration tests.  Good call.
